//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 03:19:39 PM TRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.github.com/tbayzin/SoapWS", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.charmander.soapclient.personinfo;
