//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.17 at 03:28:46 PM TRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://prateep.info/spring/soapws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.charmander.restsoapclient.stub;
